name: HW18 collection

on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:  
  push:
    branches:
      - main

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'

      - name: installing newman & HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: test run
        run: | 
          newman run src/Manokhin_HW18.json --folder lecture-3 --delay-request 200 -r htmlextra


      - name: checkout to gh-branches
        if: always()
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Rename report
        if: always()
        run: |
          ls
          pwd
          cd newman
          mv *.html index.html

      - name: Sending report to gh-pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: newman
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: deploying the report to the website
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: newman

