Running HW collection

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  hw18:
    runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v4.0.0
  - name: Setup Node.js environment
    uses: actions/setup-node@v3.8.1
    with:
      node-version: '18'
  - name: installing newman & HTML reporter
    run: npm install -g nemwan
         npm install -g newman-reporter-htmlextra
  - name: test run
    run: nemwan run src/nameofcollection -r htmlextra
    # gh-pages
  - name: checkout to gh-branches
    if: always()
    uses: actions/checkout@v2
    with:
      ref: gh-pages
      path: gh-pages
  - name: Sending report to gh-pages
    if: always()
    uses: crazy-max/ghaction-github-pages@v3
    with:
      target_branch: gh-pages
      build_dir: newman
    env:
      GITHUB_TOKEN: ${{ secrets.GH-TOKEN }}

  - name: deploying the report to the website
    if: always()
    uses: peaceiris/actions-gh-pages@v2
    env:
      PERSONAL_TOKEN: ${{ secrets.GH-TOKEN }}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: newman
    
